const SLACK_WEBHOOK_PATTERN = /^https:\/\/hooks\.slack\.com\/services\/[A-Z0-9]+\/[A-Z0-9]+\/[A-Za-z0-9]+$/;

export function isValidSlackWebhookUrl(url) {
  if (!url || typeof url !== "string") return false;
  return SLACK_WEBHOOK_PATTERN.test(url.trim());
}

function formatLabel(fmt) {
  if (fmt === "gsheets") return "Google Sheets";
  return String(fmt || "csv").toUpperCase();
}

function buildBlocks({ shopDomain, format, rowCount, filePath, scheduleLabel }) {
  const isSheet = format === "gsheets" && filePath && /^https?:\/\//.test(filePath);

  const headerText = `:bar_chart: Subscription export ready`;
  const summary =
    `*${rowCount?.toLocaleString() || 0}* subscriptions exported as *${formatLabel(format)}*` +
    (scheduleLabel ? ` · _${scheduleLabel}_` : "");

  const blocks = [
    {
      type: "header",
      text: { type: "plain_text", text: headerText, emoji: true },
    },
    {
      type: "section",
      text: { type: "mrkdwn", text: summary },
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `Store: *${shopDomain}* · Generated by SubsExport`,
        },
      ],
    },
  ];

  if (isSheet) {
    blocks.push({
      type: "actions",
      elements: [
        {
          type: "button",
          text: { type: "plain_text", text: "Open Google Sheet", emoji: true },
          url: filePath,
          style: "primary",
        },
      ],
    });
  } else if (filePath) {
    blocks.push({
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `File: \`${filePath}\` — download from your SubsExport admin → Exports.`,
        },
      ],
    });
  }

  return blocks;
}

export async function sendSlackExportNotification({
  webhookUrl,
  shopDomain,
  format,
  rowCount,
  filePath,
  scheduleLabel,
}) {
  if (!isValidSlackWebhookUrl(webhookUrl)) {
    throw new Error("Invalid Slack webhook URL");
  }

  const blocks = buildBlocks({
    shopDomain,
    format,
    rowCount,
    filePath,
    scheduleLabel,
  });

  const res = await fetch(webhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      text: `Subscription export ready: ${rowCount?.toLocaleString() || 0} rows (${formatLabel(format)})`,
      blocks,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(
      `Slack delivery failed (HTTP ${res.status}): ${body.slice(0, 200)}`,
    );
  }

  return { ok: true };
}

export async function verifySlackWebhook(webhookUrl) {
  if (!isValidSlackWebhookUrl(webhookUrl)) {
    return { valid: false, error: "URL doesn't match the Slack webhook format" };
  }

  try {
    const res = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        text: ":white_check_mark: SubsExport connected. You'll receive scheduled exports here.",
      }),
    });

    if (!res.ok) {
      const body = await res.text();
      return {
        valid: false,
        error: `Slack rejected the webhook (${res.status}): ${body.slice(0, 100)}`,
      };
    }

    return { valid: true };
  } catch (error) {
    return { valid: false, error: error.message };
  }
}
