export const SUBSCRIPTION_APPS = {
  demo: {
    name: "Demo Data",
    slug: "demo",
    authType: "none",
    phase: "A",
    description: "Connect demo data with 150 realistic fake subscriptions for testing. No API key required.",
    docsUrl: "",
    rateLimit: "Instant",
    logo: "/logos/demo.svg",
  },
  recharge: {
    name: "ReCharge",
    slug: "recharge",
    authType: "api_key",
    phase: "A",
    description: "Connect your ReCharge account using an API key from your ReCharge dashboard.",
    docsUrl: "https://docs.rechargepayments.com/",
    rateLimit: "4 req/sec",
    logo: "/logos/recharge.png",
  },
  bold: {
    name: "Bold Subscriptions",
    slug: "bold",
    authType: "oauth",
    phase: "B",
    description: "Connect Bold Subscriptions (V2) via OAuth. You'll authorize SubsExport from your Bold Account Center.",
    docsUrl: "https://developer.boldcommerce.com/guides/subscriptions-v2/public-integrations",
    rateLimit: "10 req/sec",
    logo: "/logos/bold.png",
  },
  skio: {
    name: "Skio",
    slug: "skio",
    authType: "api_key",
    phase: "A",
    description: "Connect your Skio account using an API key from your Skio dashboard (API & Integrations → API).",
    docsUrl: "https://help.skio.com/docs/using-the-skio-api",
    rateLimit: "2,000 req/min",
    logo: "/logos/skio.png",
  },
  seal: {
    name: "Seal Subscriptions",
    slug: "seal",
    authType: "api_key",
    phase: "A",
    description: "Connect Seal Subscriptions using an API token from Settings → General → API in your Seal admin.",
    docsUrl: "https://www.sealsubscriptions.com/articles/merchant-api-documentation",
    rateLimit: "Standard",
    logo: "/logos/seal.png",
  },
  paywhirl: {
    name: "PayWhirl",
    slug: "paywhirl",
    authType: "paywhirl",
    phase: "A",
    description: "Connect PayWhirl Classic or Shopify variant using an API Key + API Secret from Developer → API Keys.",
    docsUrl: "https://docs.paywhirl.com/en/articles/22086-how-to-generate-api-keys-for-custom-development",
    rateLimit: "Standard",
    logo: "/logos/paywhirl.png",
  },
  loop: {
    name: "Loop Subscriptions",
    slug: "loop",
    authType: "api_key",
    phase: "A",
    description: "Connect Loop using an API token from your Loop admin (Settings → Manage API tokens). Request Read scopes for Subscription Contracts, Orders, and Customers.",
    docsUrl: "https://developer.loopwork.co/reference",
    rateLimit: "5 req/sec",
    logo: "/logos/loop.png",
  },
};

export const PHASE_A_APPS = Object.values(SUBSCRIPTION_APPS).filter(
  (app) => app.phase === "A",
);

export const PHASE_B_APPS = Object.values(SUBSCRIPTION_APPS).filter(
  (app) => app.phase === "B",
);
